input_data_path: "ml_project/data/raw/heart.csv"
output_model_path: "ml_project/models/model_random_forest.pkl"
metric_path: "ml_project/models/metrics_random_forest.json"
splitting_params:
  val_size: 0.25
  random_state: 24
train_params:
  model_type: "RandomForestClassifier"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"
