apiVersion: v1
kind: Pod
metadata:
  name: online-inference-pod-resources
  labels:
    app: online-inference
spec:
  containers:
    - image: vbakulev/online_inference:v1
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "64Mi"
          cpu: "125m"
        limits:
          memory: "256Mi"
          cpu: "1000m"
